// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApBJld20WVcDOBW091lWqGrCnl88b8ovI',
    appId: '1:518370326908:web:7b1be3b54dfbd8e1fd0cf9',
    messagingSenderId: '518370326908',
    projectId: 'looptalk',
    authDomain: 'looptalk.firebaseapp.com',
    storageBucket: 'looptalk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdhe7eMjtX7LUc6l_vCTUdm3m-Pi9MlDY',
    appId: '1:518370326908:android:56e9fede4169d73ffd0cf9',
    messagingSenderId: '518370326908',
    projectId: 'looptalk',
    storageBucket: 'looptalk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWJnJJ_-zLZ_jecYR9kNA3dFC3dXjOmgs',
    appId: '1:518370326908:ios:a35301a590ef6de6fd0cf9',
    messagingSenderId: '518370326908',
    projectId: 'looptalk',
    storageBucket: 'looptalk.firebasestorage.app',
    iosBundleId: 'com.example.loopTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWJnJJ_-zLZ_jecYR9kNA3dFC3dXjOmgs',
    appId: '1:518370326908:ios:a35301a590ef6de6fd0cf9',
    messagingSenderId: '518370326908',
    projectId: 'looptalk',
    storageBucket: 'looptalk.firebasestorage.app',
    iosBundleId: 'com.example.loopTalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApBJld20WVcDOBW091lWqGrCnl88b8ovI',
    appId: '1:518370326908:web:fb1415fa3596698ffd0cf9',
    messagingSenderId: '518370326908',
    projectId: 'looptalk',
    authDomain: 'looptalk.firebaseapp.com',
    storageBucket: 'looptalk.firebasestorage.app',
  );
}
