// Mocks generated by Mockito 5.4.6 from annotations
// in loop_talk/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:loop_talk/model/categoria.dart' as _i2;
import 'package:loop_talk/model/comentario.dart' as _i3;
import 'package:loop_talk/model/topico.dart' as _i4;
import 'package:loop_talk/model/usuario.dart' as _i5;
import 'package:loop_talk/repository/categoria_service.dart' as _i6;
import 'package:loop_talk/repository/comentario_service.dart' as _i9;
import 'package:loop_talk/repository/loop_talk_service_api.dart' as _i11;
import 'package:loop_talk/repository/topico_service.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCategoria_0 extends _i1.SmartFake implements _i2.Categoria {
  _FakeCategoria_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeComentario_1 extends _i1.SmartFake implements _i3.Comentario {
  _FakeComentario_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTopico_2 extends _i1.SmartFake implements _i4.Topico {
  _FakeTopico_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUsuario_3 extends _i1.SmartFake implements _i5.Usuario {
  _FakeUsuario_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CategoriaService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoriaService extends _i1.Mock implements _i6.CategoriaService {
  MockCategoriaService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i8.Future<List<_i2.Categoria>> obtenerCategorias() =>
      (super.noSuchMethod(
            Invocation.method(#obtenerCategorias, []),
            returnValue: _i8.Future<List<_i2.Categoria>>.value(
              <_i2.Categoria>[],
            ),
          )
          as _i8.Future<List<_i2.Categoria>>);

  @override
  _i8.Future<_i2.Categoria> crearCategoria(_i2.Categoria? categoria) =>
      (super.noSuchMethod(
            Invocation.method(#crearCategoria, [categoria]),
            returnValue: _i8.Future<_i2.Categoria>.value(
              _FakeCategoria_0(
                this,
                Invocation.method(#crearCategoria, [categoria]),
              ),
            ),
          )
          as _i8.Future<_i2.Categoria>);

  @override
  _i8.Future<_i2.Categoria> actualizarCategoria(_i2.Categoria? categoria) =>
      (super.noSuchMethod(
            Invocation.method(#actualizarCategoria, [categoria]),
            returnValue: _i8.Future<_i2.Categoria>.value(
              _FakeCategoria_0(
                this,
                Invocation.method(#actualizarCategoria, [categoria]),
              ),
            ),
          )
          as _i8.Future<_i2.Categoria>);
}

/// A class which mocks [ComentarioService].
///
/// See the documentation for Mockito's code generation for more information.
class MockComentarioService extends _i1.Mock implements _i9.ComentarioService {
  MockComentarioService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i8.Future<List<_i3.Comentario>> obtenerRespuestas(int? topicoId) =>
      (super.noSuchMethod(
            Invocation.method(#obtenerRespuestas, [topicoId]),
            returnValue: _i8.Future<List<_i3.Comentario>>.value(
              <_i3.Comentario>[],
            ),
          )
          as _i8.Future<List<_i3.Comentario>>);

  @override
  _i8.Future<_i3.Comentario> crearRespuesta(
    int? topicoId,
    _i3.Comentario? comentario,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#crearRespuesta, [topicoId, comentario]),
            returnValue: _i8.Future<_i3.Comentario>.value(
              _FakeComentario_1(
                this,
                Invocation.method(#crearRespuesta, [topicoId, comentario]),
              ),
            ),
          )
          as _i8.Future<_i3.Comentario>);
}

/// A class which mocks [TopicoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopicoService extends _i1.Mock implements _i10.TopicoService {
  MockTopicoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i8.Future<List<_i4.Topico>> obtenerTopicos() =>
      (super.noSuchMethod(
            Invocation.method(#obtenerTopicos, []),
            returnValue: _i8.Future<List<_i4.Topico>>.value(<_i4.Topico>[]),
          )
          as _i8.Future<List<_i4.Topico>>);

  @override
  _i8.Future<_i4.Topico> crearTopico(_i4.Topico? topico, int? idCurso) =>
      (super.noSuchMethod(
            Invocation.method(#crearTopico, [topico, idCurso]),
            returnValue: _i8.Future<_i4.Topico>.value(
              _FakeTopico_2(
                this,
                Invocation.method(#crearTopico, [topico, idCurso]),
              ),
            ),
          )
          as _i8.Future<_i4.Topico>);
}

/// A class which mocks [LoopTalkServiceApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoopTalkServiceApi extends _i1.Mock
    implements _i11.LoopTalkServiceApi {
  MockLoopTalkServiceApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i8.Future<String> login(String? correo, String? contrasenia) =>
      (super.noSuchMethod(
            Invocation.method(#login, [correo, contrasenia]),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#login, [correo, contrasenia]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<_i5.Usuario> registrarUsuario({
    required String? nombre,
    required String? correo,
    required String? contrasenia,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registrarUsuario, [], {
              #nombre: nombre,
              #correo: correo,
              #contrasenia: contrasenia,
            }),
            returnValue: _i8.Future<_i5.Usuario>.value(
              _FakeUsuario_3(
                this,
                Invocation.method(#registrarUsuario, [], {
                  #nombre: nombre,
                  #correo: correo,
                  #contrasenia: contrasenia,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.Usuario>);

  @override
  _i8.Future<_i5.Usuario> obtenerUsuarioPorId(int? id, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#obtenerUsuarioPorId, [id, token]),
            returnValue: _i8.Future<_i5.Usuario>.value(
              _FakeUsuario_3(
                this,
                Invocation.method(#obtenerUsuarioPorId, [id, token]),
              ),
            ),
          )
          as _i8.Future<_i5.Usuario>);

  @override
  _i8.Future<_i5.Usuario> actualizarUsuario({
    required int? id,
    required String? nombre,
    required String? correo,
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#actualizarUsuario, [], {
              #id: id,
              #nombre: nombre,
              #correo: correo,
              #token: token,
            }),
            returnValue: _i8.Future<_i5.Usuario>.value(
              _FakeUsuario_3(
                this,
                Invocation.method(#actualizarUsuario, [], {
                  #id: id,
                  #nombre: nombre,
                  #correo: correo,
                  #token: token,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.Usuario>);

  @override
  _i8.Future<_i5.Usuario> cambiarContrasenia({
    required int? id,
    required String? nuevaContrasenia,
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#cambiarContrasenia, [], {
              #id: id,
              #nuevaContrasenia: nuevaContrasenia,
              #token: token,
            }),
            returnValue: _i8.Future<_i5.Usuario>.value(
              _FakeUsuario_3(
                this,
                Invocation.method(#cambiarContrasenia, [], {
                  #id: id,
                  #nuevaContrasenia: nuevaContrasenia,
                  #token: token,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.Usuario>);
}
